name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload backend repo contents as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-repo
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact to workspace root
        uses: actions/download-artifact@v4
        with:
          name: backend-repo
          path: .

      - name: Deploy to Azure Web App (package = repo root)
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'app-002-gen10-step3-1-py-oshima51'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EFC7B518BA6342A88C606F91CA3D1490 }}
          package: '.'
          # If you want to enforce startup via workflow instead of Procfile, uncomment below:
          # startup-command: 'gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:${PORT} app.main:app'

